CREATE TABLE events (id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, datetime timestamp, sport varchar(40), team varchar(40), details varchar(100));

CREATE TABLE sport (id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, name varchar(40));

CREATE TABLE team (id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, name varchar(40));

INSERT INTO sport (name) VALUES ('Judo');
INSERT INTO team (name) VALUES ('Judo');
INSERT INTO events (datetime, sport, team, details) VALUES ('1999-01-08 04:05:06','Judo', 'Sopron', 'semifinal');

SELECT * FROM sport;