-- Create tables

CREATE TABLE teams (id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, teamname varchar(40) NOT NULL);

CREATE TABLE sports (id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, sportname varchar(40) NOT NULL, team_id integer REFERENCES teams (id));

CREATE TABLE events (id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, calendar timestamp, sport_id integer UNIQUE REFERENCES sports (id), home_team_id integer UNIQUE REFERENCES teams (id), away_team_id integer UNIQUE REFERENCES teams (id), details varchar(100));



-- Insert into tables

INSERT INTO teams (teamname) VALUES ('Sopron'), ('Győr'),('Vienna'),('Budapest'),('Graz'),('Salzburg');
INSERT INTO sports (sportname) VALUES ('Handball'),('Football'),('Rugby');

INSERT INTO events (calendar, sport_id, home_team_id, away_team_id, details) VALUES ('1999-01-08 04:05:06', '1', '2', '3', 'Döntő');

-- Select
SELECT * FROM sports;