--Create database



-- Create tables

CREATE TABLE teams (id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, teamname varchar(40) NOT NULL);

CREATE TABLE sports (id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, sportname varchar(40) NOT NULL, team_id integer REFERENCES teams (id));

CREATE TABLE events (id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, calendar timestamp, sport_id integer UNIQUE REFERENCES sports (id), home_team_id integer UNIQUE REFERENCES teams (id), away_team_id integer UNIQUE REFERENCES teams (id), details varchar(100));



-- Insert into tables

INSERT INTO teams (teamname) VALUES ('Sopron'), ('Gyor'),('Vienna'),('Budapest'),('Graz'),('Salzburg');
INSERT INTO sports (sportname) VALUES ('Handball'),('Football'),('Rugby');

INSERT INTO events (datetime, sport_id, home_team_id, away_team_id, details) VALUES ('2022-01-08 04:05:06', '2', '4', '5', 'FINAL');


-- Select
SELECT * FROM sports;

-- sport table
exports.up = async function up(sql) {
  await sql`
	CREATE TABLE sports (id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, sportname varchar(40) NOT NULL, team_id integer REFERENCES teams (id));
	`;
};

exports.down = async function down(sql) {
  await sql`
DROP TABLE sports;
`;
};

-- events table
exports.up = async function up(sql) {
  await sql`
	CREATE TABLE events (id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, datetime timestamp, sport_id integer UNIQUE REFERENCES sports (id), home_team_id integer UNIQUE REFERENCES teams (id), away_team_id integer UNIQUE REFERENCES teams (id), details varchar(100));
	`;
};

exports.down = async function down(sql) {
  await sql`
DROP TABLE events;
`;
};

SELECT
datetime,
sports.sportname AS sport_id,
t1.teamname AS home_team_id,
t2.teamname AS away_team_id, details
FROM
events
LEFT JOIN
sports
ON
events.sport_id = sports.id
LEFT JOIN
teams t1
ON
events.home_team_id = t1.id
LEFT JOIN
teams t2
ON events.away_team_id = t2.id;
